version: "3.2"
services:


   db:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: password
     networks:
       - back

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - 8080:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: password
     networks:
       - back

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-content:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: password
     ports:
       - 80:80
       - 433:433
     networks:
       - back

networks:
   back:
volumes:
   db_data:
